# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-ps01:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Test hw01_1
      run: python -m unittest discover ./PS01_Advanced_Basics/hw01_1_log_analyzer
    - name: Test hw01_2
      run: python -m unittest discover ./PS01_Advanced_Basics/hw01_2_decorators
    - name: Test hw01_3
      run: python -m unittest discover ./PS01_Advanced_Basics/hw01_3_poker
